/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export type DiscriminatedUnionSchema = {
  bar?: any;
  foo: string;
} | {
  bar: number[];
  foo?: any;
};
